services:
    app:
        image: node:22-alpine
        working_dir: /app
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - '80:80'
        environment:
            DATABASE_URL: postgres://postgres:postgres@db:5432/watergas
        command: >
            sh -c "
            npm install &&
            npx prisma migrate deploy &&
            rm -rf dist &&
            npm run build &&
            npm run start:prod
            "
        depends_on:
            - db
        networks:
            - app-network
    db:
        image: postgres:15-alpine
        restart: always
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: watergas
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - app-network

volumes:
    postgres_data:

networks:
    app-network:
